### ISSUE TITLE
滑鼠滾輪操作失效

### ISSUE THREAD

**Issue by hdd60311** [robertabcd/PttChrome#45] opened 2018-07-06 13:43 UTC
https://www.ptt.cc/bbs/Browsers/M.1530547504.A.017.html

**Comment by hdd60311** [comment] 2018-07-12 05:43
@robertabcd 能盡快處理一下嗎，現在不能用滾輪實在不太方便

**Comment by robertabcd** [comment] 2018-07-12 06:10
Looks like it was accidentally removed in 9f629abb6320017b27a74bda08fbc7c2abe7d0d9.

**Comment by robertabcd** [comment] 2018-07-13 06:05
Duplicate of #35

**Closed as completed by robertabcd** 2018-07-13 06:05 UTC
